"""add workouts

Revision ID: 863000de5a72
Revises: a8fed563ec4c
Create Date: 2026-03-18 13:14:19.600682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863000de5a72'
down_revision = 'a8fed563ec4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_column('sets')
        batch_op.drop_column('reps')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reps', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('sets', sa.INTEGER(), nullable=False))

    op.drop_table('workout_set')
    # ### end Alembic commands ###
